### transforming code into idiomatic python
- replace traditional index manupluation with python core looping idiomatic

In [2]:
#looping over a range of a numbers-traditional apporach
for i in [0,1,2,3,4,5]:
    print(i**2,end=" ")

0 1 4 9 16 25 

In [3]:
#idiomatic programing 
for i in range(6):
    print(i**2, end=' ')

0 1 4 9 16 25 

### looping over a collection

In [4]:
colors= ['red','green','yellow','purple']
for i in range(len(colors)):
    print(colors[i],end=" ")

red green yellow purple 

In [5]:
for color in colors:
    print(color,end=" ")

red green yellow purple 

### looping backwards

In [9]:
colors= ['red','green','yellow','purple']
for i in range(len(colors)-1,-1,-1):
    print(colors[i],end=" ")

purple yellow green red 

In [11]:
for color in reversed(colors):
    print(color,end=" ")

purple yellow green red 

### looping in sorted list

In [13]:
colors= ['red','green','yellow','purple']
for color in sorted(colors,reverse=True):
     print(color,end=" ")

yellow red purple green 


- if x<=y and y<=z:
- if x<=y<=z:
- if x==True:
- if x:

### pandas

In [3]:
import pandas as pd

In [7]:
dt={'ID':[11,12,13,14,15],
    'first name':['A','B','C','D','E'],
    'comppany':['aa','bb','cc','dd','ee'],
    'address':['hyd','hyd','hyd','hyd','hyd']}
mydt = pd.DataFrame(dt)

In [9]:
print(mydt)

   ID first name comppany address
0  11          A       aa     hyd
1  12          B       bb     hyd
2  13          C       cc     hyd
3  14          D       dd     hyd
4  15          E       ee     hyd


In [11]:
import os

In [ ]:
os.chdir("pathfile")#saves to certain location

In [16]:
mydt.to_csv('workingfile.csv',index=False)

### reading the data from the csv files

In [18]:
mydata1=pd.read_csv('workingfile.csv',skiprows=[1,2,3],
                  names=["CustId","Name","Company","Address"])

In [21]:
print(mydata1)

  CustId        Name   Company  Address
0     ID  first name  comppany  address
1     14           D        dd      hyd
2     15           E        ee      hyd


In [2]:
pwd

'C:\\Users\\203'

###  Print on ly two numbers
### print large value from custid column-max
### print least value from custid column-min
### average value of custid column-sum(li)/len(li)                                                 

### Numpy- working with multi dimensional array
- numpy arrays are bit like python list
- numpy array is the data structure of Numpy lib
- its short name is numerical python or numeric python

In [4]:
import numpy as np


In [7]:
li=[1,2,3,4,5]
print(li,end=" ")

[1, 2, 3, 4, 5] 

In [8]:
array=np.array(li)
print(array)

[1 2 3 4 5]


In [10]:
a1=np.array([(1,2,3),(4,5,6)])
print(a1.shape)
a2=np.array([(1,2),(3,4),(5,6)])
print(a2.shape)

(2, 3)
(3, 2)


In [12]:
a1=np.array([(1,2,3),(4,5,6)])
a1.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [13]:
a1=np.array([(1,2,3)])
a2=np.array([(4,5,6)])
print(np.hstack((a1,a2)))

[[1 2 3 4 5 6]]


In [14]:
a1=np.array([(1,2,3)])
a2=np.array([(4,5,6)])
print(np.vstack((a1,a2)))

[[1 2 3]
 [4 5 6]]
